name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth, product, order, api-gateway]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./${{ matrix.service }}
        run: npm install

      - name: Build app
        working-directory: ./${{ matrix.service }}
        run: npm run build --if-present

      - name: Run tests (if exist)
        working-directory: ./${{ matrix.service }}
        run: |
          if [ -d "src/test" ] && ls src/test/*.test.js 1> /dev/null 2>&1; then
            echo "Running tests for ${{ matrix.service }}..."
            npm test
          else
            echo "No test files found for ${{ matrix.service }}, skipping tests."
          fi

